from pathlib import Path
import re


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected 1 occurrence, found {count}")
    return text.replace(old, new, 1)


html_path = Path("public/index.html")
html = html_path.read_text()

old_execute = '''  async function executeSelectedDecisionCandidate(){const key=state.selectedDecisionCandidate,candidate=state.decisionCandidates[key],amount=candidateUnitAmount();if(!state.connected||state.candidateBusy||!candidate||!Number.isFinite(amount)||amount<1)return;state.candidateBusy=true;renderDecisionCandidates();el("candidateExecutionStatus").textContent="Validating selected candidate against live OANDA state…";try{await refreshOpenPositions();if(openPositionPairs().has(candidate.pair)){updateDecisionDisplays();throw new Error(`${formatPair(candidate.pair)} is no longer available; candidates were refreshed.`);}const accountId=el("oandaAccountId").value.trim(),pricing=await oanda(`/v3/accounts/${encodeURIComponent(accountId)}/pricing?instruments=${encodeURIComponent(candidate.pair)}&includeUnitsAvailable=true`),available=pricing.prices?.[0]?.unitsAvailable?.default,limit=Math.max(0,Math.trunc(Number(candidate.direction>0?available?.long:available?.short)||0));if(amount>limit)throw new Error(`Requested ${amount.toLocaleString()} units exceeds ${signalWord(candidate.direction)} availability ${limit.toLocaleString()}.`);const units=candidate.direction>0?amount:-amount,payload=await oandaPost(`/v3/accounts/${encodeURIComponent(accountId)}/orders`,{order:{instrument:candidate.pair,units:String(units),type:"MARKET",timeInForce:"FOK",positionFill:"DEFAULT"}}),fill=payload.orderFillTransaction;el("candidateExecutionStatus").textContent=`${key} · ${signalWord(candidate.direction)} ${amount.toLocaleString()} ${formatPair(candidate.pair)} · ${fill?.price||"filled"} · transaction ${fill?.id||payload.lastTransactionID||"—"}`;state.selectedDecisionCandidate=null;await refreshOpenPositions();await loadTradingLedger();}catch(error){el("candidateExecutionStatus").textContent=error.message||"Selected candidate order failed.";}finally{state.candidateBusy=false;updateDecisionDisplays();renderDecisionCandidates();}}
'''
new_execute = '''  async function executeSelectedDecisionCandidate(){const key=state.selectedDecisionCandidate,candidate=state.decisionCandidates[key],amount=candidateUnitAmount();if(!state.connected||state.candidateBusy||!candidate||!Number.isFinite(amount)||amount<1)return;state.candidateBusy=true;renderDecisionCandidates();el("candidateExecutionStatus").textContent="Validating selected candidate against live OANDA state…";try{const accountId=el("oandaAccountId").value.trim(),positionsPayload=await oanda(`/v3/accounts/${encodeURIComponent(accountId)}/positions`),positions=(positionsPayload.positions||[]).filter(position=>Number(position.long?.units||0)!==0||Number(position.short?.units||0)!==0);state.openPositions=positions;renderOpenPositions();updateDecisionDisplays();if(positions.some(position=>position.instrument===candidate.pair))throw new Error(`${formatPair(candidate.pair)} is no longer available; candidates were refreshed.`);const pricing=await oanda(`/v3/accounts/${encodeURIComponent(accountId)}/pricing?instruments=${encodeURIComponent(candidate.pair)}&includeUnitsAvailable=true`),available=pricing.prices?.[0]?.unitsAvailable?.default,limit=Math.max(0,Math.trunc(Number(candidate.direction>0?available?.long:available?.short)||0));if(amount>limit)throw new Error(`Requested ${amount.toLocaleString()} units exceeds ${signalWord(candidate.direction)} availability ${limit.toLocaleString()}.`);const units=candidate.direction>0?amount:-amount,payload=await oandaPost(`/v3/accounts/${encodeURIComponent(accountId)}/orders`,{order:{instrument:candidate.pair,units:String(units),type:"MARKET",timeInForce:"FOK",positionFill:"DEFAULT"}}),fill=payload.orderFillTransaction;el("candidateExecutionStatus").textContent=`${key} · ${signalWord(candidate.direction)} ${amount.toLocaleString()} ${formatPair(candidate.pair)} · ${fill?.price||"filled"} · transaction ${fill?.id||payload.lastTransactionID||"—"}`;state.selectedDecisionCandidate=null;await refreshOpenPositions();await loadTradingLedger();}catch(error){el("candidateExecutionStatus").textContent=error.message||"Selected candidate order failed.";}finally{state.candidateBusy=false;updateDecisionDisplays();renderDecisionCandidates();}}
'''
html = replace_once(html, old_execute, new_execute, "live candidate position validation")

old_decision = '''  function updateDecisionDisplays(){const strategy=state.engineConfig.strategy,timeframe=state.engineConfig.timeframe,unavailable=openPositionPairs(),eventCandidates=INSTRUMENTS.map(pair=>{if(unavailable.has(pair))return null;const output=state.scheduleEvaluations.get(scheduleKey(pair,timeframe))?.latest?.[strategy];return output?.direction?{pair,direction:output.direction,confidence:output.confidence,source:"EVENT"}:null;}).filter(Boolean).sort((a,b)=>b.confidence-a.confidence),a=eventCandidates[0],mtfCandidates=INSTRUMENTS.map(pair=>unavailable.has(pair)?null:mtfPairDecision(pair,strategy)).filter(item=>item?.direction&&item.available>=2).sort((left,right)=>right.confidence-left.confidence||right.matches-left.matches),b=mtfCandidates[0],combined=eventCandidates.map(event=>{const mtf=mtfCandidates.find(item=>item.pair===event.pair&&item.direction===event.direction);return mtf?{pair:event.pair,direction:event.direction,confidence:(event.confidence+mtf.confidence)/2,source:"COMBINED"}:null;}).filter(Boolean).sort((left,right)=>right.confidence-left.confidence)[0],c=combined;state.decisionCandidates={A:a||null,B:b?{...b,source:"MTF"}:null,C:c||null};if(state.selectedDecisionCandidate&&!state.decisionCandidates[state.selectedDecisionCandidate])state.selectedDecisionCandidate=null;el("decisionA").textContent=a?`${formatPair(a.pair)} · ${signalWord(a.direction)} · ${formatPct(a.confidence)}`:"—";el("decisionB").textContent=b?`${formatPair(b.pair)} · ${signalWord(b.direction)} · ${formatPct(b.confidence)}`:"—";el("decisionC").textContent=c?`${formatPair(c.pair)} · ${signalWord(c.direction)} · ${formatPct(c.confidence)}`:"—";renderDecisionCandidates();}
'''
new_decision = '''  function updateDecisionDisplays(){const strategy=state.engineConfig.strategy,timeframe=state.engineConfig.timeframe,unavailable=openPositionPairs(),eventCandidates=INSTRUMENTS.map(pair=>{if(unavailable.has(pair))return null;const output=state.scheduleEvaluations.get(scheduleKey(pair,timeframe))?.latest?.[strategy];return output?.direction?{pair,direction:output.direction,confidence:output.confidence,source:"EVENT"}:null;}).filter(Boolean).sort((a,b)=>b.confidence-a.confidence),a=eventCandidates[0]||null,used=new Set(a?[a.pair]:[]),mtfCandidates=INSTRUMENTS.map(pair=>unavailable.has(pair)?null:mtfPairDecision(pair,strategy)).filter(item=>item?.direction&&item.available>=2).sort((left,right)=>right.confidence-left.confidence||right.matches-left.matches),b=mtfCandidates.find(item=>!used.has(item.pair))||null;b&&used.add(b.pair);const combinedCandidates=eventCandidates.map(event=>{const mtf=mtfCandidates.find(item=>item.pair===event.pair&&item.direction===event.direction);return mtf?{pair:event.pair,direction:event.direction,confidence:(event.confidence+mtf.confidence)/2,source:"COMBINED"}:null;}).filter(Boolean).sort((left,right)=>right.confidence-left.confidence),c=combinedCandidates.find(item=>!used.has(item.pair))||null;state.decisionCandidates={A:a,B:b?{...b,source:"MTF"}:null,C:c};if(state.selectedDecisionCandidate&&!state.decisionCandidates[state.selectedDecisionCandidate])state.selectedDecisionCandidate=null;el("decisionA").textContent=a?`${formatPair(a.pair)} · ${signalWord(a.direction)} · ${formatPct(a.confidence)}`:"—";el("decisionB").textContent=b?`${formatPair(b.pair)} · ${signalWord(b.direction)} · ${formatPct(b.confidence)}`:"—";el("decisionC").textContent=c?`${formatPair(c.pair)} · ${signalWord(c.direction)} · ${formatPct(c.confidence)}`:"—";renderDecisionCandidates();}
'''
html = replace_once(html, old_decision, new_decision, "unique A B C candidates")

html_path.write_text(html)

test_path = Path("scripts/test-runtime.mjs")
test = test_path.read_text()
test = replace_once(
    test,
    'assert.match(html,/state\\.decisionCandidates=\\{A:a\\|\\|null,B:b/);',
    'assert.match(html,/state\\.decisionCandidates=\\{A:a,B:b/);assert.match(html,/b=mtfCandidates\\.find\\(item=>!used\\.has\\(item\\.pair\\)\\)/);assert.match(html,/positionsPayload=await oanda\\(`\\/v3\\/accounts\\/\\$\\{encodeURIComponent\\(accountId\\)\\}\\/positions`\\)/);',
    "unique candidate and live validation assertions",
)
test_path.write_text(test)

Path(__file__).unlink(missing_ok=True)
