import assert from "node:assert/strict";
import worker from "../src/worker.js";
import {HtlEngine} from "../src/engine.js";
import {readFile} from "node:fs/promises";

const accountId="001-001-1234567-001",token="x".repeat(32),origin="https://cte.example";
const browser=(path,init={})=>new Request(origin+path,{...init,headers:{Origin:origin,"Sec-Fetch-Site":"same-origin",...(init.headers||{})}});
let capturedOrder=null,closed=[];
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,init={})=>{
  const value=String(url);
  if(value.endsWith("/v3/accounts"))return new Response(JSON.stringify({accounts:[{id:accountId,tags:[]}]}),{status:200});
  if(value.endsWith(`/v3/accounts/${accountId}/summary`))return new Response(JSON.stringify({account:{id:accountId,balance:"1000",NAV:"1000",marginAvailable:"900"},lastTransactionID:"1"}),{status:200});
  if(value.endsWith(`/v3/accounts/${accountId}/orders`)&&init.method==="POST"){capturedOrder=JSON.parse(init.body);return new Response(JSON.stringify({orderFillTransaction:{id:"2",price:"1.1",units:capturedOrder.order.units},lastTransactionID:"2"}),{status:200});}
  if(value.includes("/candles?")){const parsed=new URL(value);if(parsed.searchParams.has("from")){const candles=Array.from({length:180},(_,index)=>{const base=1.1+Math.sin(index/8)*.004+index*.00001;return{time:new Date(Date.UTC(2026,6,1,0,index*15)).toISOString(),complete:true,mid:{o:String(base),h:String(base+.0015),l:String(base-.0015),c:String(base+Math.sin(index/3)*.0004)},volume:10};});return new Response(JSON.stringify({candles}),{status:200});}return new Response(JSON.stringify({candles:[{time:"2026-08-04T00:00:00Z",complete:true,mid:{o:"1",h:"1.2",l:".9",c:"1.1"},volume:10}]}),{status:200});}
  if(value.endsWith(`/v3/accounts/${accountId}/positions`))return new Response(JSON.stringify({positions:[{instrument:"EUR_USD",long:{units:"10"},short:{units:"0"}}]}),{status:200});
  if(value.endsWith(`/v3/accounts/${accountId}/positions/EUR_USD/close`)){closed.push(JSON.parse(init.body));return new Response(JSON.stringify({longOrderFillTransaction:{id:"3",units:"-10",price:"1.09",pl:"1"}}),{status:200});}
  throw new Error(`Unexpected fetch: ${value}`);
};
const env={OANDA_API_KEY:token,OANDA_ACCOUNT_ID:accountId};
let response=await worker.fetch(browser("/api/oanda/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({order:{instrument:"EUR_USD",units:"25",type:"MARKET",timeInForce:"FOK",positionFill:"DEFAULT",unsafe:"removed"}})}),env);
assert.equal(response.status,200);assert.deepEqual(capturedOrder,{order:{instrument:"EUR_USD",units:"25",type:"MARKET",timeInForce:"FOK",positionFill:"DEFAULT"}});
response=await worker.fetch(browser("/api/oanda/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({order:{instrument:"BAD",units:"1",type:"MARKET",timeInForce:"FOK",positionFill:"DEFAULT"}})}),env);assert.equal(response.status,400);
response=await worker.fetch(browser("/api/oanda/proxy?path=x",{method:"POST"}),env);assert.equal(response.status,405);
response=await worker.fetch(browser("/api/engine/optimizer",{method:"PUT"}),env);assert.equal(response.status,405);
response=await worker.fetch(browser("/api/oanda/candles?instrument=EUR_USD&granularity=M15&count=60"),env);const candlePayload=await response.json();assert.equal(candlePayload.candles[0].mid.c,"1.1");assert.equal(candlePayload.candles[0].close,1.1);

class Storage{constructor(){this.map=new Map();}async get(key){if(Array.isArray(key))return new Map(key.map(item=>[item,this.map.get(item)]));return this.map.get(key);}async put(key,value){this.map.set(key,value);}async delete(key){if(Array.isArray(key))for(const item of key)this.map.delete(item);else this.map.delete(key);}async getAlarm(){return null;}async deleteAlarm(){}}
const ctx={storage:new Storage()},engine=new HtlEngine(ctx,env),config=await engine.config();
assert.equal(config.strategy,"ASSET");assert.equal(config.configurationSource,"OPTIMIZED");const forced=await engine.configure({...config,configurationSource:"FIXED"});assert.equal(forced.configurationSource,"OPTIMIZED");
engine.write=async entry=>{engine.lastWrite=entry;};
await engine.reconcile({EUR_USD:{pair:"EUR_USD",event:{direction:-1,id:"-1:t"},configuration:{primary:{length:20,filter:1,score:3,trades:8,net:12,maxDrawdown:2,winRate:.625},confirmation:null}}},token,accountId,{events:{}},config);
assert.equal(closed.length,1);assert.equal(engine.lastWrite.type,"POSITION_CLOSED");assert.equal(engine.lastWrite.htlLength,20);assert.equal(engine.lastWrite.optimizerScore,3);
response=await engine.fetch(new Request("https://engine/optimizer",{method:"PUT",headers:{"Content-Type":"application/json"},body:"{}"}));assert.equal(response.status,405);response=await engine.fetch(new Request("https://engine/compute",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pair:"EUR_USD",timeframe:"M15",startDate:"bad",endDate:"2026-08-04"})}));assert.equal(response.status,400);response=await engine.fetch(new Request("https://engine/compute",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pair:"EUR_USD",timeframe:"M15",startDate:"2026-07-01",endDate:"2026-07-03"})}));assert.equal(response.status,200);const computed=await response.json();assert.equal(computed.record.source,"COMPUTE_CONFIGURATION");assert.equal(computed.record.range.bars,180);response=await engine.fetch(new Request("https://engine/preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({selectedInstrument:"EUR_AUD",selectedTimeframe:"M30",selectedStrategy:"NAI",activeFacility:"performance",visibleBars:51})}));assert.equal(response.status,200);const storedPreferences=await response.json();assert.equal(storedPreferences.selectedInstrument,"EUR_AUD");assert.equal(storedPreferences.selectedStrategy,"NAI");response=await engine.fetch(new Request("https://engine/preferences"));assert.equal((await response.json()).visibleBars,51);

const html=await readFile(new URL("../public/index.html",import.meta.url),"utf8");
assert.match(html,/id="connectButton"[^>]*>TEST<\/button>/);assert.match(html,/selectedStrategy:"ASSET"/);assert.match(html,/configurationSource:"OPTIMIZED"/);assert.match(html,/selectChart\(event\.target\.value,state\.selectedTimeframe\)/);assert.match(html,/async function causalIndicatorSet/);assert.match(html,/token!==state\.chartCausalToken/);assert.match(html,/MAX_CANDLE_REQUESTS=3/);assert.doesNotMatch(await readFile(new URL("../src/engine.js",import.meta.url),"utf8"),/htlBuild\(data\.slice\(0,end\+1\),length\)/);assert.match(html,/payload\.stage\|\|"compute"/);assert.match(html,/\/api\/engine\/compute/);assert.match(html,/source==="COMPUTE_CONFIGURATION"/);assert.match(html,/record\.range\.bars/);assert.match(html,/button\.textContent="Computing…"/);assert.doesNotMatch(html,/function renderMacroPerformance\(\).*causalAnalysisWithConfiguration/s);assert.match(html,/id="refreshEventChart"/);assert.match(html,/refreshSelectedEventChart/);assert.match(html,/normalizeInstrumentCandles/);assert.match(html,/median>=1/);assert.match(html,/high=1\/candle\.low,low=1\/candle\.high/);assert.match(html,/Candle identity mismatch/);assert.match(html,/decisionCandidateStrip/);assert.match(html,/executeSelectedDecisionCandidate/);assert.match(html,/state\.decisionCandidates=\{A:a,B:b/);assert.match(html,/b=mtfCandidates\.find\(item=>!used\.has\(item\.pair\)\)/);assert.match(html,/positionsPayload=await oanda\(`\/v3\/accounts\/\$\{encodeURIComponent\(accountId\)\}\/positions`\)/);assert.match(html,/openPositionPairs\(\)/);assert.match(html,/causalIndicatorSetFast/);assert.match(html,/causalAnalysisWithConfiguration/);assert.doesNotMatch(html,/prepareIndicators\(data\.slice\(0,index\+1\)/);assert.match(html,/\/api\/platform\/preferences/);assert.match(html,/NAI:\{price:\[\],z:/);assert.match(html,/const zDefinitions=indicatorSet\.z/);assert.match(html,/activeFacility:/);assert.match(html,/const assetAt=/);assert.doesNotMatch(html,/htlBuild\(data\.slice\(0,index\+1\),length\)/);assert.match(html,/eventLoadedKey/);assert.match(html,/await loadTradeCapacity\(\);void loadChart\(\);void loadSchedule\(\);/);assert.doesNotMatch(html,/Fixed controls/);assert.match(html,/macroStartDate/);assert.match(html,/microStartDate/);assert.match(html,/runPlatformDiagnostic/);assert.match(html,/MAX_BACKGROUND_CANDLE_REQUESTS=2/);assert.doesNotMatch(html,/structuredClone\s*\(/);assert.doesNotMatch(html,/\/api\/engine\/optimizer[^\n]+method:"PUT"/);
globalThis.fetch=originalFetch;
console.log("Runtime routes, JPY chart normalization, event refresh, selectable candidates, persistence, diagnostics, causal performance, and no-data orchestration contracts verified.");
