const API="https://api-fxtrade.oanda.com";
const PAIRS=["EUR_USD","GBP_USD","USD_JPY","USD_CAD","USD_CHF","AUD_USD","NZD_USD","EUR_GBP","EUR_JPY","EUR_CHF","EUR_AUD","EUR_CAD","EUR_NZD","GBP_JPY","GBP_CHF","GBP_AUD","GBP_CAD","GBP_NZD","AUD_JPY","AUD_CHF","AUD_CAD","AUD_NZD","NZD_JPY","NZD_CHF","NZD_CAD","CAD_JPY","CAD_CHF","CHF_JPY"];
const MTF_TIMEFRAMES=["W","D","H4","H1","M30","M15","M5","M1","S30","S5"],TIMEFRAMES=new Set(MTF_TIMEFRAMES),TIMEFRAME_SECONDS={W:604800,D:86400,H4:14400,H1:3600,M30:1800,M15:900,M5:300,M1:60,S30:30,S5:5},DECISION_MODES=new Set(["EVENT","MTF","COMBINED"]),STRATEGIES=new Set(["ASSET","DARE_N","DARE","COMBO","NAI","APEX"]),DEFAULT_CONFIG={timeframe:"M15",htlLength:10,decisionMode:"EVENT",strategy:"ASSET",confirmationStrategy:"NONE",filter:0,configurationSource:"OPTIMIZED"},CANDLE_COUNT=650,MAX_COMPUTE_BARS=2500,OPTIMIZER_VERSION=4,OPTIMIZER_TTL_MS=7*24*60*60*1000,AI_MODEL="@cf/nvidia/nemotron-3-120b-a12b";

const response=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const mean=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const median=values=>{if(!values.length)return null;const v=[...values].sort((a,b)=>a-b),m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2;};

async function callOanda(path,token,init={}){
  const result=await fetch(API+path,{method:init.method||"GET",headers:{Authorization:`Bearer ${token}`,Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{})},body:init.body,redirect:"manual",cache:"no-store"});
  const payload=await result.json().catch(()=>({}));
  if(!result.ok)throw Object.assign(new Error(payload.errorMessage||payload.errorCode||`OANDA HTTP ${result.status}`),{status:result.status,payload});
  return payload;
}

function secrets(env){const token=String(env.OANDA_API_KEY||"").trim(),configured=String(env.OANDA_ACCOUNT_ID||"").trim();if(token.length<20||!configured)throw new Error("OANDA secrets unavailable");return{token,configured};}

async function liveAccount(token,configured){
  const payload=await callOanda("/v3/accounts",token),accounts=payload.accounts||[];
  const account=accounts.find(item=>item.id===configured&&!item.tags?.includes("MT4"))||accounts.find(item=>String(item.id||"").endsWith("-001")&&!item.tags?.includes("MT4"));
  if(!account)throw new Error("Authorized non-MT4 account ending -001 not found");
  return account.id;
}

function seriesAverage(values,length){let total=0;return values.map((value,index)=>{total+=value;if(index>=length)total-=values[index-length];return total/length;});}
function seriesStdev(values,length){const out=Array(values.length).fill(null);if(values.length<length)return out;for(let i=length-1;i<values.length;i++){const slice=values.slice(i-length+1,i+1);if(!slice.every(Number.isFinite))continue;const m=mean(slice);out[i]=Math.sqrt(mean(slice.map(value=>(value-m)**2)));}return out;}
function seriesWma(values,length){const out=Array(values.length).fill(null),den=length*(length+1)/2;for(let i=length-1;i<values.length;i++){const slice=values.slice(i-length+1,i+1);if(slice.every(Number.isFinite))out[i]=slice.reduce((sum,value,index)=>sum+(index+1)*value,0)/den;}return out;}
const pairAverage=(left,right)=>left.map((value,index)=>Number.isFinite(value)&&Number.isFinite(right[index])?(value+right[index])/2:null);
const norm=(left,right,deviation)=>left.map((value,index)=>Number.isFinite(value)&&Number.isFinite(right[index])&&Number.isFinite(deviation[index])&&deviation[index]!==0?(value-right[index])/deviation[index]:null);
const inverse=(z,deviation,center)=>z.map((value,index)=>Number.isFinite(value)&&Number.isFinite(deviation[index])&&Number.isFinite(center[index])?(-value*deviation[index])+center[index]:null);
function cross(left,right,index){if(index<1)return 0;const v=[left[index],right[index],left[index-1],right[index-1]];if(!v.every(Number.isFinite))return 0;if(left[index]>right[index]&&left[index-1]<=right[index-1])return 1;if(left[index]<right[index]&&left[index-1]>=right[index-1])return-1;return 0;}

function htlCore(data,length){
  const close=data.map(c=>c.close),high=data.map(c=>c.high),low=data.map(c=>c.low),average=seriesAverage(close,length),deviation=seriesStdev(close,length),zero=deviation.map(value=>Number.isFinite(value)&&value!==0?0:null),u=zero.map((value,index)=>Number.isFinite(value)&&Number.isFinite(deviation[index])?(value*deviation[index])+average[index]:null),wmaU=seriesWma(u,length),zu=norm(u,wmaU,deviation),i=inverse(zu,deviation,wmaU),hl2=high.map((value,index)=>(value+low[index])/2),mui=pairAverage(i,u),wmaMui=seriesWma(mui,length),zui=norm(mui,wmaMui,deviation),iuz=zui.map(value=>Number.isFinite(value)?-value:null),ui=inverse(zui,deviation,wmaMui),uim=pairAverage(mui,ui),wmaUim=seriesWma(uim,length),zim=norm(uim,wmaUim,deviation),uir=inverse(zim,deviation,wmaUim),miu=pairAverage(uim,uir),wmaMiu=seriesWma(miu,length),zmiu=norm(miu,wmaMiu,deviation),ia=zmiu.map((value,index)=>Number.isFinite(value)&&Number.isFinite(deviation[index])&&Number.isFinite(wmaMiu[index])?((value+1)*deviation[index])+wmaMiu[index]:null),id=zmiu.map((value,index)=>Number.isFinite(value)&&Number.isFinite(deviation[index])&&Number.isFinite(wmaMiu[index])?((value-1)*deviation[index])+wmaMiu[index]:null),up=pairAverage(ia,id),wmaUp=seriesWma(up,length),zup=norm(close,wmaUp,deviation),upr=inverse(zup,deviation,wmaUp);
  return{hl2,mui,zui,iuz,ui,upr,zup,puz:zup.map(value=>Number.isFinite(value)?-value:null)};
}

function htlBuild(data,length){
  const series=htlCore(data,length),families=[[series.hl2,series.upr],[series.mui,series.ui],[series.zui,series.iuz]],sourceCrosses=[];
  for(let index=1;index<data.length;index++){const directions=families.map(pair=>cross(pair[0],pair[1],index)).filter(Boolean),vote=directions.reduce((sum,value)=>sum+value,0);if(vote)sourceCrosses.push({index,direction:Math.sign(vote)});}
  const anchors=[];let active=null;
  const finalize=(episode,end,status)=>{let price=episode.direction>0?-Infinity:Infinity,extremeIndex=episode.index;for(let index=episode.index;index<=end;index++){const value=episode.direction>0?data[index].high:data[index].low;if((episode.direction>0&&value>price)||(episode.direction<0&&value<price)){price=value;extremeIndex=index;}}return{index:extremeIndex,price,direction:episode.direction,status};};
  for(const event of sourceCrosses){if(active&&event.direction!==active.direction){anchors.push(finalize(active,Math.max(active.index,event.index-1),"FINAL"));active=event;}else if(!active)active=event;}
  if(active)anchors.push(finalize(active,data.length-1,"PROVISIONAL"));anchors.sort((a,b)=>a.index-b.index);const dedup=[];for(const anchor of anchors){if(dedup.length&&dedup.at(-1).index===anchor.index)dedup[dedup.length-1]=anchor;else dedup.push(anchor);}
  const asset=Array(data.length).fill(null);if(dedup.length){for(let index=0;index<=dedup[0].index;index++)asset[index]=dedup[0].price;for(let p=1;p<dedup.length;p++){const from=dedup[p-1],to=dedup[p],span=Math.max(1,to.index-from.index);for(let index=from.index;index<=to.index;index++)asset[index]=from.price+(to.price-from.price)*((index-from.index)/span);}const last=dedup.at(-1);for(let index=last.index;index<data.length;index++)asset[index]=last.price;}
  const assetMean=seriesWma(asset,length),assetDeviation=seriesStdev(asset,length),assetZ=norm(asset,assetMean,assetDeviation),recovered=inverse(assetZ,assetDeviation,assetMean),sourceTotal=Array(data.length).fill(0);let total=0,crossPosition=0;for(let index=0;index<data.length;index++){while(crossPosition<sourceCrosses.length&&sourceCrosses[crossPosition].index===index){total++;crossPosition++;}sourceTotal[index]=total;}
  const meanAsset=pairAverage(asset,recovered),meanCenter=seriesWma(meanAsset,length),meanInverse=meanAsset.map((value,index)=>Number.isFinite(value)&&Number.isFinite(meanCenter[index])?(2*meanCenter[index])-value:null);
  const assetCenter=seriesWma(asset,length),inverseCenter=seriesWma(recovered,length),naiAsset=norm(asset,assetCenter,seriesStdev(asset,length)),naiInverse=norm(recovered,inverseCenter,seriesStdev(recovered,length));
  const dareNAsset=norm(meanAsset,seriesWma(meanAsset,length),seriesStdev(meanAsset,length)),dareNInverse=norm(meanInverse,seriesWma(meanInverse,length),seriesStdev(meanInverse,length));
  return{asset,inverse:recovered,meanAsset,meanInverse,naiAsset,naiInverse,dareNAsset,dareNInverse,zup:series.zup,puz:series.puz,sourceTotal};
}

function relationEvents(left,right,filter=0){const events=[];let active=0;for(let index=1;index<Math.min(left.length,right.length);index++){if(![left[index],right[index]].every(Number.isFinite))continue;const spread=left[index]-right[index],direction=spread>filter?1:spread<-filter?-1:0;if(direction&&direction!==active){events.push({index,direction});active=direction;}}return events;}
function strategyEvents(data,length,strategy,filter=0){const htl=htlBuild(data,length),exact=(left,right)=>{const events=[];for(let index=1;index<data.length;index++){const direction=cross(left,right,index);if(direction)events.push({index,direction});}return events;};if(strategy==="ASSET")return exact(htl.asset,htl.inverse);if(strategy==="DARE")return exact(htl.meanAsset,htl.meanInverse);if(strategy==="DARE_N")return relationEvents(htl.dareNAsset,htl.dareNInverse,filter);if(strategy==="NAI")return relationEvents(htl.naiAsset,htl.naiInverse,filter);if(strategy==="APEX"){const events=[];let active=0;for(let index=0;index<data.length;index++){const z=htl.zup[index],p=htl.puz[index];if(![z,p].every(Number.isFinite))continue;const direction=z<=-filter&&p>=filter?1:z>=filter&&p<=-filter?-1:0;if(direction&&direction!==active){events.push({index,direction});active=direction;}}return events;}const members=[strategyEvents(data,length,"DARE",filter),strategyEvents(data,length,"NAI",filter)],state=[0,0],byIndex=new Map();members.forEach((events,member)=>events.forEach(event=>{if(!byIndex.has(event.index))byIndex.set(event.index,[]);byIndex.get(event.index).push([member,event.direction]);}));const events=[];let active=0;for(let index=0;index<data.length;index++){for(const [member,direction] of byIndex.get(index)||[])state[member]=direction;const direction=state[0]&&state[0]===state[1]?state[0]:0;if(direction&&direction!==active){events.push({index,direction});active=direction;}}return events;}
function currentEvent(data,length,strategy="ASSET",filter=0){
  const crosses=strategyEvents(data,length,strategy,filter);
  if(!crosses.length)return null;const current=crosses.at(-1),start=data[current.index];return{direction:current.direction,startTime:start.time,openPrice:start.close,bars:data.length-current.index,id:`${current.direction}:${start.time}`};
}

function htlCausal(data,length){const series=htlCore(data,length),families=[[series.hl2,series.upr],[series.mui,series.ui],[series.zui,series.iuz]],crosses=new Map();for(let index=1;index<data.length;index++){const directions=families.map(pair=>cross(pair[0],pair[1],index)).filter(Boolean),vote=directions.reduce((sum,value)=>sum+value,0);if(vote)crosses.set(index,{index,direction:Math.sign(vote)});}const asset=Array(data.length).fill(null),recovered=Array(data.length).fill(null),assetMean=Array(data.length).fill(null),finalized=[];let active=null;const begin=event=>({index:event.index,direction:event.direction,price:event.direction>0?data[event.index].high:data[event.index].low,extremeIndex:event.index}),update=(episode,index)=>{const price=episode.direction>0?data[index].high:data[index].low;if((episode.direction>0&&price>episode.price)||(episode.direction<0&&price<episode.price)){episode.price=price;episode.extremeIndex=index;}},dedup=anchors=>{const out=[];for(const anchor of anchors.sort((a,b)=>a.index-b.index)){if(out.length&&out.at(-1).index===anchor.index)out[out.length-1]=anchor;else out.push(anchor);}return out;},assetAt=(anchors,index)=>{if(!anchors.length)return null;if(index<=anchors[0].index)return anchors[0].price;for(let position=1;position<anchors.length;position++){const from=anchors[position-1],to=anchors[position];if(index<=to.index){const span=Math.max(1,to.index-from.index);return from.price+(to.price-from.price)*((index-from.index)/span);}}return anchors.at(-1).price;},first=Math.max(1,length*3-1),denominator=length*(length+1)/2;for(let index=0;index<data.length;index++){const event=crosses.get(index);if(event){if(!active)active=begin(event);else if(event.direction!==active.direction){finalized.push({index:active.extremeIndex,price:active.price,direction:active.direction,status:"FINAL"});active=begin(event);}}if(active)update(active,index);if(index<first||!active)continue;const anchors=dedup([...finalized,{index:active.extremeIndex,price:active.price,direction:active.direction,status:"PROVISIONAL"}]),start=Math.max(0,index-length+1),window=[];for(let cursor=start;cursor<=index;cursor++)window.push(assetAt(anchors,cursor));if(window.length!==length||!window.every(Number.isFinite))continue;const current=window.at(-1),weighted=window.reduce((sum,value,position)=>sum+(position+1)*value,0)/denominator,average=mean(window),deviation=Math.sqrt(mean(window.map(value=>(value-average)**2)));asset[index]=current;assetMean[index]=weighted;recovered[index]=deviation>0?(2*weighted)-current:null;}return{asset,inverse:recovered,assetMean,series};}
function causalIndicatorSet(data,length){const htl=htlCausal(data,length),meanAsset=pairAverage(htl.asset,htl.inverse),meanCenter=seriesWma(meanAsset,length),meanInverse=meanAsset.map((value,index)=>Number.isFinite(value)&&Number.isFinite(meanCenter[index])?(2*meanCenter[index])-value:null),assetCenter=seriesWma(htl.asset,length),inverseCenter=seriesWma(htl.inverse,length),naiAsset=norm(htl.asset,assetCenter,seriesStdev(htl.asset,length)),naiInverse=norm(htl.inverse,inverseCenter,seriesStdev(htl.inverse,length)),dareNAsset=norm(meanAsset,seriesWma(meanAsset,length),seriesStdev(meanAsset,length)),dareNInverse=norm(meanInverse,seriesWma(meanInverse,length),seriesStdev(meanInverse,length));return{asset:htl.asset,inverse:htl.inverse,meanAsset,meanInverse,dareNAsset,dareNInverse,naiAsset,naiInverse,zup:htl.series.zup,puz:htl.series.puz};}
function causalSnapshots(data,length){const indicators=causalIndicatorSet(data,length);return data.map((_,index)=>({asset:indicators.asset[index],inverse:indicators.inverse[index],meanAsset:indicators.meanAsset[index],meanInverse:indicators.meanInverse[index],dareNAsset:indicators.dareNAsset[index],dareNInverse:indicators.dareNInverse[index],naiAsset:indicators.naiAsset[index],naiInverse:indicators.naiInverse[index],zup:indicators.zup[index],puz:indicators.puz[index]}));}
function snapshotDirection(snapshot,strategy,filter=0){if(!snapshot)return 0;const relation=(left,right,threshold=0)=>Number.isFinite(left)&&Number.isFinite(right)?left-right>threshold?1:left-right<-threshold?-1:0:0;if(strategy==="ASSET")return relation(snapshot.asset,snapshot.inverse);if(strategy==="DARE")return relation(snapshot.meanAsset,snapshot.meanInverse);if(strategy==="DARE_N")return relation(snapshot.dareNAsset,snapshot.dareNInverse,filter);if(strategy==="NAI")return relation(snapshot.naiAsset,snapshot.naiInverse,filter);if(strategy==="APEX")return Number.isFinite(snapshot.zup)&&Number.isFinite(snapshot.puz)?snapshot.zup<=-filter&&snapshot.puz>=filter?1:snapshot.zup>=filter&&snapshot.puz<=-filter?-1:0:0;const dare=relation(snapshot.meanAsset,snapshot.meanInverse),nai=relation(snapshot.naiAsset,snapshot.naiInverse,filter);return dare&&dare===nai?dare:0;}
function causalStrategyEvents(snapshots,strategy,filter=0){const events=[];let active=0;for(let index=0;index<snapshots.length;index++){const direction=snapshotDirection(snapshots[index],strategy,filter);if(direction&&direction!==active){events.push({index,direction});active=direction;}}return events;}
function walkForwardScore(data,events,pair){const pip=pair.endsWith("JPY")?100:10000,foldStarts=[.4,.55,.7,.85].map(value=>Math.floor(data.length*value)),foldEnds=[...foldStarts.slice(1),data.length],trades=[];for(let index=0;index<events.length-1;index++){const current=events[index],next=events[index+1],entryIndex=current.index+1,exitIndex=next.index+1;if(entryIndex>=data.length||exitIndex>=data.length||exitIndex<=entryIndex)continue;if(!foldStarts.some((start,fold)=>entryIndex>=start&&exitIndex<foldEnds[fold]))continue;const entry=data[entryIndex].open,exit=data[exitIndex].open,range=data.slice(entryIndex,exitIndex+1),gross=(exit-entry)*current.direction*pip,net=gross-1,mfe=(current.direction>0?Math.max(...range.map(candle=>candle.high))-entry:entry-Math.min(...range.map(candle=>candle.low)))*pip,mae=(current.direction>0?entry-Math.min(...range.map(candle=>candle.low)):Math.max(...range.map(candle=>candle.high))-entry)*pip;trades.push({net,mfe:Math.max(0,mfe),mae:Math.max(0,mae)});}const wins=trades.filter(trade=>trade.net>.05),losses=trades.filter(trade=>trade.net<-.05),flats=trades.length-wins.length-losses.length,net=trades.reduce((sum,trade)=>sum+trade.net,0),average=trades.length?net/trades.length:0,grossWin=wins.reduce((sum,trade)=>sum+trade.net,0),grossLoss=-losses.reduce((sum,trade)=>sum+trade.net,0);let equity=0,peak=0,maxDrawdown=0;for(const trade of trades){equity+=trade.net;peak=Math.max(peak,equity);maxDrawdown=Math.max(maxDrawdown,peak-equity);}const variance=trades.length?mean(trades.map(trade=>(trade.net-average)**2)):0,uncertainty=Math.sqrt(variance/Math.max(1,trades.length)),mfe=trades.reduce((sum,trade)=>sum+trade.mfe,0),mae=trades.reduce((sum,trade)=>sum+trade.mae,0);return{trades:trades.length,wins:wins.length,losses:losses.length,flats,net,average,mfeMae:mae?mfe/mae:mfe?Infinity:null,maxDrawdown,profitFactor:grossLoss?grossWin/grossLoss:grossWin?Infinity:null,recoveryFactor:maxDrawdown?net/maxDrawdown:net>0?Infinity:null,winRate:trades.length?wins.length/trades.length:0,score:trades.length>=5?net-.5*maxDrawdown-uncertainty:-Infinity,estimatedCostPips:1,validation:"ROLLING_ORIGIN_CAUSAL"};}
function optimizeDataset(data,pair){const lengths=[10,20,30,50].filter(length=>length*3<data.length),filters={ASSET:[0],DARE_N:[0,.5,1,2],DARE:[0],COMBO:[0,.5,1,2],NAI:[0,.5,1,2],APEX:[0,1,2]},config={},snapshots=new Map(lengths.map(length=>[length,causalSnapshots(data,length)]));for(const strategy of STRATEGIES){let best={length:lengths[0]||10,filter:filters[strategy][0],score:-Infinity,trades:0,net:0,maxDrawdown:0,winRate:0,validation:"ROLLING_ORIGIN_CAUSAL"};for(const length of lengths)for(const filter of filters[strategy]){const stats=walkForwardScore(data,causalStrategyEvents(snapshots.get(length),strategy,filter),pair);if(stats.score>best.score)best={length,filter,...stats};}config[strategy]=best;}return config;}

function normalizeCandles(payload){return(payload.candles||[]).filter(c=>c.complete&&c.mid).map(c=>({time:c.time,open:Number(c.mid.o),high:Number(c.mid.h),low:Number(c.mid.l),close:Number(c.mid.c),volume:Number(c.volume||0)})).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite));}
async function candles(pair,token,timeframe,count=CANDLE_COUNT){const q=new URLSearchParams({price:"M",granularity:timeframe,count:String(count),smooth:"false"});return normalizeCandles(await callOanda(`/v3/instruments/${pair}/candles?${q}`,token));}
async function candlesForRange(pair,token,timeframe,startDate,endDate){const start=new Date(`${startDate}T00:00:00.000Z`),end=new Date(`${endDate}T23:59:59.999Z`);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start>end)throw Object.assign(new Error("Invalid Compute Configuration date range."),{status:400});const estimated=Math.ceil((end-start)/(TIMEFRAME_SECONDS[timeframe]*1000))+2;if(estimated>MAX_COMPUTE_BARS)throw Object.assign(new Error(`Selected ${timeframe} date range is too large for one causal optimization (${estimated.toLocaleString()} estimated bars; maximum ${MAX_COMPUTE_BARS.toLocaleString()}). Reduce the date range.`),{status:400});const q=new URLSearchParams({price:"M",granularity:timeframe,from:start.toISOString(),to:end.toISOString(),smooth:"false",includeFirst:"true"}),data=normalizeCandles(await callOanda(`/v3/instruments/${pair}/candles?${q}`,token));if(data.length>MAX_COMPUTE_BARS)throw Object.assign(new Error(`OANDA returned ${data.length.toLocaleString()} bars; maximum ${MAX_COMPUTE_BARS.toLocaleString()}. Reduce the date range.`),{status:400});return data;}

async function notify(env,entry){
  const text=`CTE ${entry.type}: ${entry.pair||"system"} ${entry.direction||""} ${entry.message||""}`.trim();
  if(env.SENDGRID_API_KEY&&env.ALERT_EMAIL_TO&&env.ALERT_EMAIL_FROM)await fetch("https://api.sendgrid.com/v3/mail/send",{method:"POST",headers:{Authorization:`Bearer ${env.SENDGRID_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({personalizations:[{to:[{email:env.ALERT_EMAIL_TO}]}],from:{email:env.ALERT_EMAIL_FROM},subject:"CTE Compound",content:[{type:"text/plain",value:text}]})}).catch(()=>{});
  if(env.TWILIO_ACCOUNT_SID&&env.TWILIO_AUTH_TOKEN&&env.TWILIO_FROM&&env.SMS_TO){const body=new URLSearchParams({To:env.SMS_TO,From:env.TWILIO_FROM,Body:text});await fetch(`https://api.twilio.com/2010-04-01/Accounts/${env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:"POST",headers:{Authorization:`Basic ${btoa(`${env.TWILIO_ACCOUNT_SID}:${env.TWILIO_AUTH_TOKEN}`)}`,"Content-Type":"application/x-www-form-urlencoded"},body}).catch(()=>{});}
}

function normalizeConfig(value={}){const timeframe=TIMEFRAMES.has(value.timeframe)?value.timeframe:DEFAULT_CONFIG.timeframe,htlLength=Math.max(3,Math.min(200,Math.trunc(Number(value.htlLength))||DEFAULT_CONFIG.htlLength)),decisionMode=DECISION_MODES.has(value.decisionMode)?value.decisionMode:DEFAULT_CONFIG.decisionMode,strategy=STRATEGIES.has(value.strategy)?value.strategy:DEFAULT_CONFIG.strategy,confirmationStrategy=value.confirmationStrategy==="NONE"||STRATEGIES.has(value.confirmationStrategy)?value.confirmationStrategy:DEFAULT_CONFIG.confirmationStrategy,filter=Math.max(0,Math.min(10,Number(value.filter)||0)),configurationSource="OPTIMIZED";return{timeframe,htlLength,decisionMode,strategy,confirmationStrategy,filter,configurationSource};}
function normalizeUiPreferences(value={}){const date=input=>/^\d{4}-\d{2}-\d{2}$/.test(String(input||""))?String(input):"",integer=(input,min,max,fallback)=>Math.max(min,Math.min(max,Math.trunc(Number(input))||fallback));return{selectedInstrument:PAIRS.includes(value.selectedInstrument)?value.selectedInstrument:"EUR_USD",selectedTimeframe:TIMEFRAMES.has(value.selectedTimeframe)?value.selectedTimeframe:"M15",selectedStrategy:STRATEGIES.has(value.selectedStrategy)?value.selectedStrategy:"ASSET",selectedScheduleStrategy:STRATEGIES.has(value.selectedScheduleStrategy)?value.selectedScheduleStrategy:"ASSET",activeFacility:["analysis","event","performance"].includes(value.activeFacility)?value.activeFacility:"analysis",visibleBars:integer(value.visibleBars,30,300,120),rightIndent:integer(value.rightIndent,0,260,72),crosshairEnabled:value.crosshairEnabled!==false,eventPair:PAIRS.includes(value.eventPair)?value.eventPair:"EUR_USD",eventTimeframe:TIMEFRAMES.has(value.eventTimeframe)?value.eventTimeframe:"M15",eventLength:integer(value.eventLength,3,200,10),eventStrategy:STRATEGIES.has(value.eventStrategy)?value.eventStrategy:"ASSET",eventVisibleBars:integer(value.eventVisibleBars,30,300,120),eventRightIndent:integer(value.eventRightIndent,0,260,72),eventCrosshairEnabled:value.eventCrosshairEnabled!==false,macroStartDate:date(value.macroStartDate),macroEndDate:date(value.macroEndDate),microStartDate:date(value.microStartDate),microEndDate:date(value.microEndDate),minimumUnits:integer(value.minimumUnits,1,100000000,1000),updatedAt:new Date().toISOString()};}
function configFingerprint(config){return JSON.stringify({timeframe:config.timeframe,decisionMode:config.decisionMode,strategy:config.strategy,confirmationStrategy:config.confirmationStrategy,htlLength:config.htlLength,filter:config.filter,configurationSource:config.configurationSource,optimizerVersion:OPTIMIZER_VERSION});}
function currentOptimizer(records){const now=Date.now();return Object.fromEntries(Object.entries(records||{}).filter(([,record])=>record?.version===OPTIMIZER_VERSION&&now-Date.parse(record.computedAt||record.stamp||0)<OPTIMIZER_TTL_MS));}
function clientOrderId(pair,eventId){let hash=2166136261;for(const character of `${pair}|${eventId}`){hash^=character.charCodeAt(0);hash=Math.imul(hash,16777619);}return `cte-${pair}-${(hash>>>0).toString(16)}`;}

export class HtlEngine{
  constructor(ctx,env){this.ctx=ctx;this.env=env;this.running=false;}
  async fetch(request){const url=new URL(request.url),path=url.pathname;if(path==="/status")return response(await this.status());if(path==="/preferences"&&request.method==="GET")return response(normalizeUiPreferences((await this.ctx.storage.get("uiPreferences"))||{}));if(path==="/preferences"&&request.method==="PUT"){const preferences=normalizeUiPreferences(await request.json());await this.ctx.storage.put("uiPreferences",preferences);return response(preferences);}if(path==="/config"&&request.method==="GET")return response(await this.config());if(path==="/config"&&request.method==="PUT")return response(await this.configure(await request.json()));if(path==="/optimizer"&&request.method==="GET")return response({version:OPTIMIZER_VERSION,records:currentOptimizer(await this.ctx.storage.get("optimizer"))});if(path==="/optimizer"&&request.method==="PUT")return response({error:"Optimizer records are server-managed."},405);if(path==="/compute"&&request.method==="POST"){try{return response(await this.computeConfiguration(await request.json()));}catch(error){return response({error:String(error?.message||error),stage:error?.stage||"compute"},Number(error?.status)||500);}}if(path==="/ledger"){const limit=Math.max(1,Math.min(5000,Number(url.searchParams.get("limit"))||500)),index=(await this.ctx.storage.get("ledgerIndex"))||[],keys=index.slice(0,limit),records=keys.length?await this.ctx.storage.get(keys):new Map(),ledger=keys.map(key=>records.get(key)).filter(Boolean);return response({ledger:ledger.length?ledger:((await this.ctx.storage.get("ledger"))||[]).slice(0,limit),retained:index.length||((await this.ctx.storage.get("ledger"))||[]).length});}if(path==="/tick"&&request.method==="POST"){await this.tick();return response(await this.status());}return response({error:"Not found"},404);}
  async alarm(){await this.ctx.storage.deleteAlarm();}
  async config(){const state=(await this.ctx.storage.get("state"))||{};return normalizeConfig(state.config);}
  async configure(value){const state=(await this.ctx.storage.get("state"))||{events:{}},prior=normalizeConfig(state.config),next=normalizeConfig(value);if(configFingerprint(prior)!==configFingerprint(next)){state.events={};state.directions=null;state.requirements=null;state.lastCandle=null;state.mtf={};state.mtfDecisionDirections={};state.mtfRotation=0;state.mtfFingerprint=configFingerprint(next);state.initialized=false;}state.config=next;await this.ctx.storage.put("state",state);await this.write({type:"CONFIGURATION",strategy:next.strategy,message:`${next.timeframe} · ${next.strategy} · length ${next.htlLength} · filter ${next.filter} · ${next.decisionMode} · ${next.configurationSource}`});return next;}
  async status(){const state=(await this.ctx.storage.get("state"))||{},config=normalizeConfig(state.config),optimizer=currentOptimizer(await this.ctx.storage.get("optimizer")),ai=(await this.ctx.storage.get("aiTelemetry"))||{};return{armed:true,running:this.running,...config,triggerMode:"new-completed-candle-only",positionManagement:"all-open-positions",mtfCoverage:Object.values(state.mtf||{}).filter(snapshot=>snapshot?.fingerprint===configFingerprint(config)).length,optimizerVersion:OPTIMIZER_VERSION,optimizerCoverage:Object.keys(optimizer).length,optimizerTotal:PAIRS.length*MTF_TIMEFRAMES.length,optimizerCycleIndex:Number(state.optimizerCycleIndex||0),optimizerLastDataset:state.optimizerLastDataset||null,optimizerLastRun:state.optimizerLastRun||null,optimizerLastError:state.optimizerLastError||null,lastTransactionId:state.lastTransactionId||null,transactionSyncError:state.transactionSyncError||null,pendingOrders:Object.keys(state.pendingOrders||{}).length,ai:{model:AI_MODEL,binding:Boolean(this.env.AI),...ai},lastCandle:state.lastCandle||null,lastRun:state.lastRun||null,lastError:state.lastError||null,processedPairs:Object.keys(state.events||{}).length};}
  async write(entry,sendNotification=true){const record={...entry,time:new Date().toISOString(),ledgerId:crypto.randomUUID()},key=`ledger:${record.time}:${record.ledgerId}`,index=(await this.ctx.storage.get("ledgerIndex"))||[];await this.ctx.storage.put(key,record);index.unshift(key);const removed=index.splice(5000);await this.ctx.storage.put("ledgerIndex",index);if(removed.length)await this.ctx.storage.delete(removed);const legacy=(await this.ctx.storage.get("ledger"))||[];legacy.unshift(record);await this.ctx.storage.put("ledger",legacy.slice(0,500));if(sendNotification)await notify(this.env,record);}
  async recordAiDecision(decision){const now=new Date().toISOString(),day=now.slice(0,10),prior=(await this.ctx.storage.get("aiTelemetry"))||{},daily=prior.daily?.date===day?prior.daily:{date:day,invocations:0,selections:0,fallbacks:0},invoked=Boolean(decision.invoked),selected=decision.status==="SELECTED";if(invoked)daily.invocations++;if(selected)daily.selections++;else daily.fallbacks++;const telemetry={totalInvocations:Number(prior.totalInvocations||0)+(invoked?1:0),totalSelections:Number(prior.totalSelections||0)+(selected?1:0),totalFallbacks:Number(prior.totalFallbacks||0)+(selected?0:1),daily,last:{...decision,time:now}};await this.ctx.storage.put("aiTelemetry",telemetry);await this.write({type:selected?"AI_DECISION":"AI_FALLBACK",pair:decision.selectedPair||null,message:`Nemotron · ${decision.status} · ${decision.candidateCount} candidates · ${decision.latencyMs} ms${decision.reason?` · ${decision.reason}`:""}`},false);return telemetry;}
  async saveOptimizer(){throw Object.assign(new Error("Optimizer records are server-managed."),{status:405});}
  pairConfig(config,optimizer,pair,timeframe){const normalize=(entry,fallback)=>{const length=Number(entry?.length),filter=Number(entry?.filter);return{length:Math.max(3,Math.min(200,Number.isFinite(length)?Math.trunc(length):fallback.htlLength)),filter:Math.max(0,Math.min(10,Number.isFinite(filter)?filter:fallback.filter)),score:Number.isFinite(entry?.score)?entry.score:null,trades:Number.isFinite(entry?.trades)?entry.trades:null,net:Number.isFinite(entry?.net)?entry.net:null,maxDrawdown:Number.isFinite(entry?.maxDrawdown)?entry.maxDrawdown:null,winRate:Number.isFinite(entry?.winRate)?entry.winRate:null};},fixed=normalize(null,config);if(config.configurationSource!=="OPTIMIZED")return{...config,primary:fixed,confirmation:config.confirmationStrategy==="NONE"?null:fixed};const strategies=optimizer?.[`${pair}|${timeframe}`]?.config||{},primary=normalize(strategies[config.strategy],config),confirmation=config.confirmationStrategy==="NONE"?null:normalize(strategies[config.confirmationStrategy],config);return{...config,htlLength:primary.length,filter:primary.filter,primary,confirmation};}
  async computeConfiguration(value={}){let stage="validation";try{const pair=String(value.pair||"").toUpperCase(),timeframe=String(value.timeframe||"").toUpperCase(),startDate=String(value.startDate||""),endDate=String(value.endDate||"");if(!PAIRS.includes(pair))throw Object.assign(new Error("Invalid Compute Configuration currency pair."),{status:400});if(!TIMEFRAMES.has(timeframe))throw Object.assign(new Error("Invalid Compute Configuration timeframe."),{status:400});if(!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||!/^\d{4}-\d{2}-\d{2}$/.test(endDate))throw Object.assign(new Error("Start date and end date are required."),{status:400});stage="credentials";const {token}=secrets(this.env);stage="oanda-range";const data=await candlesForRange(pair,token,timeframe,startDate,endDate);if(data.length<80)throw Object.assign(new Error(`Insufficient completed candles for Compute Configuration: ${data.length}. Select a wider date range.`),{status:400});stage="causal-optimization";const config=optimizeDataset(data,pair),stamp=data.at(-1)?.time||new Date().toISOString();stage="durable-storage";const records=(await this.ctx.storage.get("optimizer"))||{},key=`${pair}|${timeframe}`,record={version:OPTIMIZER_VERSION,stamp,computedAt:new Date().toISOString(),source:"COMPUTE_CONFIGURATION",range:{startDate,endDate,firstCandle:data[0]?.time||null,lastCandle:data.at(-1)?.time||null,bars:data.length},config};records[key]=record;await this.ctx.storage.put("optimizer",records);return{key,record};}catch(error){if(!error.stage)error.stage=stage;throw error;}}
  async optimizeNext(state,token){const total=PAIRS.length*MTF_TIMEFRAMES.length,index=Number(state.optimizerCycleIndex||0)%total,pair=PAIRS[index%PAIRS.length],timeframe=MTF_TIMEFRAMES[Math.floor(index/PAIRS.length)],key=`${pair}|${timeframe}`,records=(await this.ctx.storage.get("optimizer"))||{},existing=records[key];state.optimizerCycleIndex=(index+1)%total;if(existing?.source==="COMPUTE_CONFIGURATION"&&Date.now()-Date.parse(existing.computedAt||0)<OPTIMIZER_TTL_MS){state.optimizerLastDataset=key;state.optimizerLastRun=new Date().toISOString();state.optimizerLastError=null;return{records:currentOptimizer(records),key,record:existing};}const data=await candles(pair,token,timeframe),config=optimizeDataset(data,pair),stamp=data.at(-1)?.time||new Date().toISOString(),record={version:OPTIMIZER_VERSION,stamp,computedAt:new Date().toISOString(),source:"SERVER",range:{startDate:null,endDate:null,firstCandle:data[0]?.time||null,lastCandle:data.at(-1)?.time||null,bars:data.length},config};records[key]=record;await this.ctx.storage.put("optimizer",records);state.optimizerLastDataset=key;state.optimizerLastRun=new Date().toISOString();state.optimizerLastError=null;return{records:currentOptimizer(records),key,record};}
  async scan(token,config,timeframe=config.timeframe,optimizer={}){const rows=[],errors=[];for(const pair of PAIRS)try{const effective=this.pairConfig(config,optimizer,pair,timeframe),data=await candles(pair,token,timeframe),event=currentEvent(data,effective.primary.length,effective.strategy,effective.primary.filter),confirmation=effective.confirmationStrategy==="NONE"?null:currentEvent(data,effective.confirmation.length,effective.confirmationStrategy,effective.confirmation.filter);if(event&&(!confirmation||confirmation.direction===event.direction))rows.push({pair,event,configuration:{primary:effective.primary,confirmation:effective.confirmation}});}catch(error){errors.push({pair,error:String(error?.message||error)});}if(errors.length)await this.write({type:"SCAN_PARTIAL",message:`${timeframe}: ${rows.length} pairs loaded, ${errors.length} failed`,failures:errors},false);return rows;}
  async syncTransactions(state,token,accountId){
    if(!state.lastTransactionId){const summary=await callOanda(`/v3/accounts/${accountId}/summary`,token);state.lastTransactionId=summary.lastTransactionID||null;return;}
    const payload=await callOanda(`/v3/accounts/${accountId}/transactions/sinceid?id=${encodeURIComponent(state.lastTransactionId)}`,token),seen=new Set(state.transactionIds||[]);
    for(const transaction of payload.transactions||[]){if(!transaction.id||seen.has(transaction.id))continue;seen.add(transaction.id);await this.write({type:"OANDA_TRANSACTION",transaction:transaction.id,transactionType:transaction.type,pair:transaction.instrument||null,direction:Number(transaction.units)>0?"BUY":Number(transaction.units)<0?"SELL":null,units:transaction.units?Math.abs(Number(transaction.units)):null,price:transaction.price||null,realizedPL:transaction.pl??null,financing:transaction.financing??null,commission:transaction.commission??null,accountBalance:transaction.accountBalance??null,clientOrderId:transaction.clientExtensions?.id||transaction.orderClientExtensions?.id||null,reason:transaction.reason||null},false);}
    state.transactionIds=[...seen].slice(-2000);state.lastTransactionId=payload.lastTransactionID||state.lastTransactionId;state.transactionSyncError=null;
  }
  decisionContext(candidate,config){const primary=candidate?.configuration?.primary||{length:config.htlLength,filter:config.filter,score:null,trades:null,net:null,maxDrawdown:null,winRate:null},confirmation=candidate?.configuration?.confirmation||null;return{strategy:config.strategy,confirmationStrategy:config.confirmationStrategy,decisionMode:config.decisionMode,timeframe:config.timeframe,htlLength:primary.length,filter:primary.filter,configurationSource:config.configurationSource,optimizerScore:primary.score??null,optimizerTrades:primary.trades??null,optimizerNet:primary.net??null,optimizerDrawdown:primary.maxDrawdown??null,optimizerWinRate:primary.winRate??null,confirmationHtlLength:confirmation?.length??null,confirmationFilter:confirmation?.filter??null};}
  closeRecord(fill,{pair,direction,event=null,message,context={}}){return{type:"POSITION_CLOSED",pair,direction,units:Math.abs(Number(fill.units)||0),price:fill.price||null,realizedPL:fill.pl??null,financing:fill.financing??null,commission:fill.commission??null,accountBalance:fill.accountBalance??null,transaction:fill.id||null,event,message,...context};}
  async closePosition(pair,existing,longUnits,shortUnits,token,accountId,event,message,context={}){
    const body=existing>0?{longUnits:"ALL"}:{shortUnits:"ALL"},result=await callOanda(`/v3/accounts/${accountId}/positions/${pair}/close`,token,{method:"PUT",body:JSON.stringify(body)}),fill=result.longOrderFillTransaction||result.shortOrderFillTransaction;
    if(!fill){const rejected=result.longOrderRejectTransaction||result.shortOrderRejectTransaction,reason=rejected?.rejectReason||rejected?.reason||"OANDA returned no close fill";await this.write({type:"CLOSE_REJECTED",pair,direction:existing>0?"BUY":"SELL",units:existing>0?longUnits:shortUnits,transaction:rejected?.id||result.lastTransactionID||null,event,message:reason,...context});return null;}
    await this.write(this.closeRecord(fill,{pair,direction:existing>0?"BUY":"SELL",event,message,context}));return fill;
  }
  async reconcile(requirements,token,accountId,state,config){
    const payload=await callOanda(`/v3/accounts/${accountId}/positions`,token),positions=payload.positions||[];
    for(const position of positions){
      if(!PAIRS.includes(position.instrument))continue;
      const longUnits=Number(position.long?.units||0),shortUnits=Math.abs(Number(position.short?.units||0)),existing=longUnits>0?1:shortUnits>0?-1:0,requirement=requirements[position.instrument],required=Number(requirement?.event?.direction??requirement??0);
      if(!existing||!required||existing===required)continue;
      const context=this.decisionContext(requirement&&typeof requirement==="object"?requirement:null,config),event=requirement?.event?.id||state.events?.[position.instrument]||null;
      await this.closePosition(position.instrument,existing,longUnits,shortUnits,token,accountId,event,"Position opposed current strategy direction",context);
    }
  }
  mtfCandidates(state,rows,lastCandle,fingerprint){const byPair=new Map(rows.map(row=>[row.pair,row]));return PAIRS.map(pair=>{let score=0,count=0;for(const timeframe of MTF_TIMEFRAMES){const snapshot=state.mtf?.[timeframe];if(snapshot?.fingerprint!==fingerprint)continue;const direction=Number(snapshot.directions?.[pair]||0);if(direction){score+=direction;count++;}}const direction=Math.sign(score),confidence=count?Math.abs(score)/count:0,row=byPair.get(pair);return direction&&count>=3&&row?{pair,event:{...row.event,direction,id:`MTF:${direction}:${lastCandle}`},confidence,count,configuration:row.configuration}:null;}).filter(Boolean).sort((left,right)=>right.confidence-left.confidence||right.count-left.count);}
  async tick(){
    if(this.running)return;this.running=true;let state=(await this.ctx.storage.get("state"))||{events:{},initialized:false};
    try{
      const config=normalizeConfig(state.config),fingerprint=configFingerprint(config);state.config=config;if(state.mtfFingerprint!==fingerprint){state.mtf={};state.mtfRotation=0;state.mtfFingerprint=fingerprint;}let optimizer=currentOptimizer(await this.ctx.storage.get("optimizer"));const{token,configured}=secrets(this.env),accountId=await liveAccount(token,configured);try{await this.syncTransactions(state,token,accountId);}catch(error){state.transactionSyncError=error.message||"Transaction synchronization failed";}try{optimizer=(await this.optimizeNext(state,token)).records;}catch(error){state.optimizerLastError=error.message||"Optimizer failure";}const rotationIndex=Number(state.mtfRotation||0)%MTF_TIMEFRAMES.length,rotationTimeframe=MTF_TIMEFRAMES[rotationIndex],rotationRows=await this.scan(token,config,rotationTimeframe,optimizer);state.mtf=state.mtf||{};state.mtf[rotationTimeframe]={fingerprint,directions:Object.fromEntries(rotationRows.map(row=>[row.pair,row.event.direction])),updated:new Date().toISOString()};state.mtfRotation=(rotationIndex+1)%MTF_TIMEFRAMES.length;const probe=await candles("EUR_USD",token,config.timeframe,2),lastCandle=probe.at(-1)?.time;
      if(!lastCandle)return;
      if(lastCandle===state.lastCandle){
        if(!state.requirements){const rows=rotationTimeframe===config.timeframe?rotationRows:await this.scan(token,config,config.timeframe,optimizer);state.directions=Object.fromEntries(rows.map(row=>[row.pair,row.event.direction]));state.requirements=Object.fromEntries(rows.map(row=>[row.pair,row]));state.events=Object.fromEntries(rows.map(row=>[row.pair,row.event.id]));state.initialized=true;}
        await this.reconcile(state.requirements,token,accountId,state,config);
        state.lastRun=new Date().toISOString();state.lastError=null;return;
      }
      const rows=rotationTimeframe===config.timeframe?rotationRows:await this.scan(token,config,config.timeframe,optimizer);
      state.directions=Object.fromEntries(rows.map(row=>[row.pair,row.event.direction]));
      const requirements=Object.fromEntries(rows.map(row=>[row.pair,row])),mtfNow=this.mtfCandidates(state,rows,lastCandle,fingerprint);state.requirements=requirements;
      await this.reconcile(requirements,token,accountId,state,config);
      if(!state.initialized){state.events=Object.fromEntries(rows.map(row=>[row.pair,row.event.id]));state.mtfDecisionDirections=Object.fromEntries(mtfNow.map(row=>[row.pair,row.event.direction]));state.initialized=true;await this.write({type:"INITIALIZED",message:`${rows.length} HTL events registered`});}
      else{
        const eventCandidates=rows.filter(row=>state.events[row.pair]!==row.event.id&&row.event.startTime===lastCandle).sort((a,b)=>b.event.bars-a.event.bars),priorMtf=state.mtfDecisionDirections||{},mtfCandidates=mtfNow.filter(row=>Number(priorMtf[row.pair]||0)!==row.event.direction),combined=eventCandidates.map(event=>{const mtf=mtfNow.find(item=>item.pair===event.pair&&item.event.direction===event.event.direction);return mtf?{...event,confidence:mtf.confidence,count:mtf.count}:null;}).filter(Boolean).sort((left,right)=>right.confidence-left.confidence),decisionCandidates=config.decisionMode==="EVENT"?eventCandidates:config.decisionMode==="MTF"?mtfCandidates:combined;
        let candidate=null;if(decisionCandidates.length)candidate=await this.choose(decisionCandidates);
        if(candidate)await this.execute(candidate,token,accountId,state);
        for(const row of rows)state.events[row.pair]=row.event.id;
        state.mtfDecisionDirections=Object.fromEntries(mtfNow.map(row=>[row.pair,row.event.direction]));
      }
      state.lastCandle=lastCandle;state.lastRun=new Date().toISOString();state.lastError=null;
    }catch(error){state.lastRun=new Date().toISOString();state.lastError=error.message||"Engine failure";await this.write({type:"ERROR",message:state.lastError});}
    finally{await this.ctx.storage.put("state",state);if(await this.ctx.storage.getAlarm()!==null)await this.ctx.storage.deleteAlarm();this.running=false;}
  }
  async choose(candidates){
    if(candidates.length===1)return candidates[0];
    const table=candidates.map(row=>({pair:row.pair,direction:row.event.direction>0?"BUY":"SELL",eventId:row.event.id,bars:row.event.bars,openPrice:row.event.openPrice,confidence:Number.isFinite(row.confidence)?row.confidence:null,mtfCount:Number.isFinite(row.count)?row.count:null,optimizerScore:row.configuration?.primary?.score??null,optimizerTrades:row.configuration?.primary?.trades??null,optimizerNet:row.configuration?.primary?.net??null,optimizerDrawdown:row.configuration?.primary?.maxDrawdown??null,optimizerWinRate:row.configuration?.primary?.winRate??null,configuration:row.configuration||null})),fallback=candidates[0],started=Date.now();
    if(!this.env.AI){await this.recordAiDecision({invoked:false,status:"AI_BINDING_UNAVAILABLE",latencyMs:0,candidateCount:candidates.length,candidates:table.map(item=>item.pair),selectedPair:fallback.pair,reason:"Deterministic first-candidate fallback"}).catch(()=>{});return fallback;}
    try{
      const result=await this.env.AI.run(AI_MODEL,{messages:[{role:"system",content:"Select exactly one candidate from the supplied completed HTL reversal events. Rank only eligible candidates using event age, multi-timeframe confidence, and causal optimizer evidence including sample size, net result, and drawdown. Return JSON only: {\"pair\":\"PAIR\",\"reason\":\"concise reason\"}. Never invent a pair or change its direction."},{role:"user",content:JSON.stringify(table)}],response_format:{type:"json_object"},max_completion_tokens:160}),content=result.response||result.result||result.choices?.[0]?.message?.content||result.choices?.[0]?.text||"{}",parsed=typeof content==="string"?JSON.parse(content):content,selected=candidates.find(row=>row.pair===parsed?.pair),latencyMs=Date.now()-started;
      if(!selected){await this.recordAiDecision({invoked:true,status:"INVALID_RESPONSE_FALLBACK",latencyMs,candidateCount:candidates.length,candidates:table.map(item=>item.pair),selectedPair:fallback.pair,reason:"Model did not return an eligible pair"}).catch(()=>{});return fallback;}
      await this.recordAiDecision({invoked:true,status:"SELECTED",latencyMs,candidateCount:candidates.length,candidates:table.map(item=>item.pair),selectedPair:selected.pair,reason:String(parsed.reason||"").slice(0,240)}).catch(()=>{});return selected;
    }catch(error){await this.recordAiDecision({invoked:true,status:"ERROR_FALLBACK",latencyMs:Date.now()-started,candidateCount:candidates.length,candidates:table.map(item=>item.pair),selectedPair:fallback.pair,reason:String(error?.message||"Workers AI request failed").slice(0,240)}).catch(()=>{});return fallback;}
  }
  async execute(candidate,token,accountId,state){
    const{pair,event}=candidate,direction=event.direction>0?"BUY":"SELL",accountPayload=await callOanda(`/v3/accounts/${accountId}`,token),account=accountPayload.account||{},position=(account.positions||[]).find(item=>item.instrument===pair),longUnits=Number(position?.long?.units||0),shortUnits=Math.abs(Number(position?.short?.units||0)),existing=longUnits>0?1:shortUnits>0?-1:0;
    const config=normalizeConfig(state.config),context=this.decisionContext(candidate,config);
    state.pendingOrders=state.pendingOrders||{};
    const pending=state.pendingOrders[pair];
    if(pending?.event===event.id){
      if(existing===event.direction){await this.write({type:"ORDER_RECONCILED",pair,direction,event:event.id,...context,clientOrderId:pending.clientId,message:"OANDA position confirms the pending entry; duplicate submission suppressed"});delete state.pendingOrders[pair];await this.ctx.storage.put("state",state);return;}
      try{const found=await callOanda(`/v3/accounts/${accountId}/orders/@${encodeURIComponent(pending.clientId)}`,token);await this.write({type:"ORDER_RECONCILED",pair,direction,transaction:found.order?.id||found.lastTransactionID||null,event:event.id,...context,message:`Existing OANDA order ${pending.clientId} recovered; duplicate submission suppressed`});delete state.pendingOrders[pair];await this.ctx.storage.put("state",state);return;}
      catch(error){if(Number(error?.status)!==404)throw error;delete state.pendingOrders[pair];}
    }
    if(existing===event.direction){await this.write({type:"NO_ORDER",pair,direction,message:"Existing position already matches event",...context});return;}
    if(existing){const fill=await this.closePosition(pair,existing,longUnits,shortUnits,token,accountId,event.id,"Opposite strategy event",context);if(!fill)return;}
    const summary=(await callOanda(`/v3/accounts/${accountId}/summary`,token)).account||{};if(Number(summary.marginAvailable)<=0){await this.write({type:"NO_ORDER",pair,direction,message:"No margin available",...context});return;}
    const pricing=await callOanda(`/v3/accounts/${accountId}/pricing?instruments=${pair}&includeUnitsAvailable=true`,token),available=pricing.prices?.[0]?.unitsAvailable?.default,units=Math.max(0,Math.trunc(Number(event.direction>0?available?.long:available?.short)||0));if(!units){await this.write({type:"NO_ORDER",pair,direction,message:"No directional units available",...context});return;}const minimumUnits=normalizeUiPreferences((await this.ctx.storage.get("uiPreferences"))||{}).minimumUnits;if(units<minimumUnits){await this.write({type:"NO_ORDER",pair,direction,units,message:`Directional availability ${units} is below minimum units ${minimumUnits}`,...context});return;}
    const signed=event.direction>0?units:-units,clientId=clientOrderId(pair,event.id),order={order:{instrument:pair,units:String(signed),type:"MARKET",timeInForce:"FOK",positionFill:"DEFAULT",clientExtensions:{id:clientId,tag:"cte-compound",comment:event.id.slice(0,64)}}};state.pendingOrders[pair]={clientId,event:event.id,direction,units,createdAt:new Date().toISOString()};await this.ctx.storage.put("state",state);const result=await callOanda(`/v3/accounts/${accountId}/orders`,token,{method:"POST",body:JSON.stringify(order)}),fill=result.orderFillTransaction;
    if(!fill){const rejected=result.orderRejectTransaction||result.orderCancelTransaction,reason=rejected?.rejectReason||rejected?.reason||"OANDA returned no order fill";delete state.pendingOrders[pair];await this.ctx.storage.put("state",state);await this.write({type:"ORDER_REJECTED",pair,direction,units,transaction:rejected?.id||result.lastTransactionID||null,event:event.id,message:reason,...context});return;}
    delete state.pendingOrders[pair];await this.ctx.storage.put("state",state);await this.write({type:"ORDER_FILLED",pair,direction,units:Math.abs(Number(fill.units)||units),transaction:fill.id||result.lastTransactionID||null,clientOrderId:clientId,price:fill.price||null,accountBalance:fill.accountBalance??null,event:event.id,...context});
  }
}
