import horizonWorker from "./worker-horizon-base.js";
export { HtlEngine } from "./engine-signal-provenance.js";

const headers={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers});
function assertSameOrigin(request){const url=new URL(request.url),origin=request.headers.get("Origin"),site=request.headers.get("Sec-Fetch-Site");if(origin&&origin!==url.origin)throw Object.assign(new Error("Cross-origin request rejected."),{status:403});if(!origin&&!site)throw Object.assign(new Error("Browser-origin request required."),{status:403});if(site&&!['same-origin','same-site','none'].includes(site))throw Object.assign(new Error("Cross-site request rejected."),{status:403});}
async function indicatorOnlyAuthority(env){const response=await env.HTL_ENGINE.getByName("live").fetch("https://engine/control/indicatorOnly");if(!response.ok)throw new Error(`Indicator Only authority check failed: HTTP ${response.status}`);const payload=await response.json().catch(()=>null);if(!payload?.indicatorOnly)throw new Error("Indicator Only authority state is unavailable");return payload.indicatorOnly;}
async function injectPlatformContracts(response,url){const type=response.headers.get("Content-Type")||"";if(!(url.pathname==="/"||url.pathname.endsWith(".html")||type.includes("text/html")))return response;let html=await response.text();html=html.replace('<script src="/market-mentor.js"></script>','<script src="/market-mentor.js"></script>\n  <script src="/indicator-only.js"></script>');html=html.replace('<script src="/platform-horizon-runtime.js"></script>','<script src="/horizon-strategy-contract.js"></script>\n  <script src="/platform-horizon-runtime.js"></script>\n  <script src="/platform-horizon-qualified-direction.js"></script>');html=html.replace('</body>','  <script src="/unified-chart.js"></script>\n  <script src="/chart-indicator-ownership.js"></script>\n  <script src="/chart-ioi-iom.js"></script>\n  <script src="/directional-ownership.js"></script>\n  <script src="/ioi-iom-performance.js"></script>\n  <script src="/htl-schedule-integrity.js"></script>\n  <script src="/analytical-facilities.js"></script>\n  <script src="/forensic-runtime-repair.js"></script>\n  <script src="/schedule-dataset-accounting.js"></script>\n  <script src="/htl-signal-panel.js"></script>\n  <script src="/analytical-table-sorting.js"></script>\n  <script src="/runtime-integrity.js"></script>\n</body>');const responseHeaders=new Headers(response.headers);responseHeaders.delete("Content-Length");responseHeaders.set("Cache-Control","no-store");return new Response(html,{status:response.status,statusText:response.statusText,headers:responseHeaders});}

export default{
  async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/oanda/order"&&request.method==="POST"){try{assertSameOrigin(request);const io=await indicatorOnlyAuthority(env);if(io.enabled)return json({error:`Indicator Only is active for ${io.ticketCount||1} ticket${Number(io.ticketCount||1)===1?"":"s"}. Disengage IO before submitting a manual order.`,indicatorOnly:io},409);}catch(error){if(Number(error?.status)===403)return json({error:error?.message||"Order rejected."},403);if(String(error?.message||"").startsWith("Indicator Only is active"))return json({error:error.message},409);if(error?.message?.includes("Cross-" )||error?.message?.includes("Browser-origin"))return json({error:error.message},403);return json({error:"Order route authority unavailable; order withheld.",details:error?.message||String(error)},503);}}return injectPlatformContracts(await horizonWorker.fetch(request,env,ctx),url);},
  async scheduled(event,env,ctx){return horizonWorker.scheduled(event,env,ctx);}
};