import horizonWorker from "./worker-horizon-base.js";
export { HtlEngine } from "./engine-live-signal-price.js";
import { requireCloudflareAccess } from "./access-auth.js";
import { PAIRS, TIMEFRAMES } from "./horizon-platform-engine.js";
import {
  COMPOUND_MCP_PROTOCOL_VERSION,
  COMPOUND_SCHEDULE_VERSION,
  evaluateCompoundScheduleDataset,
  normalizeScheduleStrategies,
  projectOptimizerSchedule,
  requiredScheduleBars,
} from "./compound-schedule.js";
import {
  CAPITALIZATION_REQUEST_BARS,
  COMPOUND_CAPITALIZATION_VERSION,
  buildCapitalizationEvaluationRow,
} from "./compound-capitalization.js";
import { timeframeHierarchy } from "./mas-im-calculator.js";

const headers={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers});
const MCP_SCHEDULE_CACHE_MS=4000,MCP_SCHEDULE_CONCURRENCY=8,mcpScheduleCache=new Map();
const MCP_CAPITALIZATION_CACHE_MS=4000,MCP_CAPITALIZATION_CONCURRENCY=8,mcpCapitalizationCache=new Map();
const MCP_STRATEGIES=["ASSET","DARE_N","DARE","COMBO","NAI","APEX"];
const MCP_TOOLS=[
  {name:"get_compound_schedule",description:"Returns the live compact 28-pair × 11-timeframe CTE Compound schedule through the server data plane. Optimized settings come from Durable Object storage; current registered indicator state is calculated server-side from completed OANDA candles through the existing Worker candle cache. No browser 308-request candle fan-out is required.",inputSchema:{type:"object",properties:{strategies:{type:"array",items:{type:"string",enum:MCP_STRATEGIES},description:"Registered indicators to include. ASSET is always included for the HTL event clock."}},required:[]}},
  {name:"get_capitalization_snapshot",description:"Returns the 28-pair Capitalization Model / Evaluation Table snapshot for one signal timeframe. MAS/IM hierarchy, transition statistics, Pips/Hr, regime, and four-slot ranking inputs are calculated server-side from completed candles through the Worker cache so the browser does not preload the pair × hierarchy candle universe.",inputSchema:{type:"object",properties:{timeframe:{type:"string",enum:TIMEFRAMES},strategy:{type:"string",enum:MCP_STRATEGIES}},required:["timeframe"]}},
];

function assertSameOrigin(request){const url=new URL(request.url),origin=request.headers.get("Origin"),site=request.headers.get("Sec-Fetch-Site");if(origin&&origin!==url.origin)throw Object.assign(new Error("Cross-origin request rejected."),{status:403});if(!origin&&!site)throw Object.assign(new Error("Browser-origin request required."),{status:403});if(site&&!['same-origin','same-site','none'].includes(site))throw Object.assign(new Error("Cross-site request rejected."),{status:403});}
async function indicatorOnlyAuthority(env){const response=await env.HTL_ENGINE.getByName("live").fetch("https://engine/control/indicatorOnly");if(!response.ok)throw new Error(`Indicator Only authority check failed: HTTP ${response.status}`);const payload=await response.json().catch(()=>null);if(!payload?.indicatorOnly)throw new Error("Indicator Only authority state is unavailable");return payload.indicatorOnly;}
async function optimizerScheduleProjection(env){const response=await env.HTL_ENGINE.getByName("live").fetch("https://engine/optimizer");if(!response.ok)throw new Error(`Optimizer schedule projection failed: HTTP ${response.status}`);const payload=await response.json().catch(()=>({})),records=payload?.records||{};return{scheduleVersion:COMPOUND_SCHEDULE_VERSION,optimizerVersion:payload?.version??null,optimizerHistoryBars:payload?.optimizerHistoryBars??null,strategyEngineVersion:payload?.strategyEngineVersion??null,performanceVersion:payload?.performanceVersion??null,total:PAIRS.length*TIMEFRAMES.length,coverage:Object.keys(records).length,rows:projectOptimizerSchedule(records,PAIRS,TIMEFRAMES)};}
function internalCandleRequest(sourceRequest,pair,timeframe,count){const url=new URL(sourceRequest.url);url.pathname="/api/oanda/candles";url.search=new URLSearchParams({instrument:pair,granularity:timeframe,count:String(count)}).toString();return new Request(url,{method:"GET",headers:sourceRequest.headers});}
async function runPool(items,limit,worker){let cursor=0;const runners=Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const index=cursor++;await worker(items[index],index);}});await Promise.all(runners);}
async function liveCompoundSchedule(request,env,ctx,strategiesInput){const strategies=normalizeScheduleStrategies(strategiesInput),projection=await optimizerScheduleProjection(env),latestStamp=projection.rows.reduce((latest,row)=>String(row.computedAt||row.stamp||"")>latest?String(row.computedAt||row.stamp||""):latest,""),cacheKey=`${strategies.join(",")}|${latestStamp}`,cached=mcpScheduleCache.get(cacheKey),now=Date.now();if(cached&&cached.expires>now)return cached.value;const started=Date.now(),rows=new Array(projection.rows.length);await runPool(projection.rows,MCP_SCHEDULE_CONCURRENCY,async(row,index)=>{try{const count=requiredScheduleBars(row.settings,strategies),response=await horizonWorker.fetch(internalCandleRequest(request,row.pair,row.timeframe,count),env,ctx),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||payload?.message||`Candle HTTP ${response.status}`);const evaluated=evaluateCompoundScheduleDataset(payload?.candles||[],row.settings,strategies);rows[index]={...row,optimizerAvailable:row.available,available:true,...evaluated};}catch(error){rows[index]={...row,optimizerAvailable:row.available,available:false,error:String(error?.message||error),strategies:{},htlCurrentEvent:null};}});const coverage=rows.filter(row=>row.available).length,value={scheduleVersion:COMPOUND_SCHEDULE_VERSION,protocolVersion:COMPOUND_MCP_PROTOCOL_VERSION,source:"MCP_SERVER_DATA_PLANE",optimizerVersion:projection.optimizerVersion,optimizerHistoryBars:projection.optimizerHistoryBars,total:projection.total,coverage,failureCount:projection.total-coverage,strategies,generatedAt:new Date().toISOString(),durationMs:Date.now()-started,rows};mcpScheduleCache.clear();mcpScheduleCache.set(cacheKey,{expires:Date.now()+MCP_SCHEDULE_CACHE_MS,value});return value;}
async function liveCapitalizationSnapshot(request,env,ctx,timeframeInput,strategyInput){
  const timeframe=String(timeframeInput||"H1").trim().toUpperCase(),strategy=String(strategyInput||"ASSET").trim().toUpperCase().replace(/[\s/-]+/g,"_");
  if(!TIMEFRAMES.includes(timeframe))throw Object.assign(new Error(`Invalid capitalization timeframe: ${timeframe}`),{code:-32602});
  if(!MCP_STRATEGIES.includes(strategy))throw Object.assign(new Error(`Invalid capitalization strategy: ${strategy}`),{code:-32602});
  const hierarchy=timeframeHierarchy(timeframe);if(!hierarchy.length)throw Object.assign(new Error(`Unsupported MAS/IM timeframe: ${timeframe}`),{code:-32602});
  const projection=await optimizerScheduleProjection(env),latestStamp=projection.rows.reduce((latest,row)=>String(row.computedAt||row.stamp||"")>latest?String(row.computedAt||row.stamp||""):latest,""),cacheKey=`${timeframe}|${strategy}|${latestStamp}`,cached=mcpCapitalizationCache.get(cacheKey),now=Date.now();
  if(cached&&cached.expires>now)return cached.value;
  const started=Date.now(),frames=Object.fromEntries(PAIRS.map(pair=>[pair,{}])),frameErrors=Object.fromEntries(PAIRS.map(pair=>[pair,[]])),jobs=PAIRS.flatMap(pair=>hierarchy.map(tf=>({pair,tf})));
  await runPool(jobs,MCP_CAPITALIZATION_CONCURRENCY,async({pair,tf})=>{try{const response=await horizonWorker.fetch(internalCandleRequest(request,pair,tf,CAPITALIZATION_REQUEST_BARS),env,ctx),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||payload?.message||`Candle HTTP ${response.status}`);const candles=Array.isArray(payload?.candles)?payload.candles:[];if(candles.length<80)throw new Error(`INSUFFICIENT_CAPITALIZATION_CANDLES:${candles.length}:80`);frames[pair][tf]=candles;}catch(error){frameErrors[pair].push(`${tf}:${String(error?.message||error)}`);}});
  const activeRows=new Map(projection.rows.filter(row=>row.timeframe===timeframe).map(row=>[row.pair,row]));
  const rows=PAIRS.map(pair=>{const optimizer=activeRows.get(pair)||null,row=buildCapitalizationEvaluationRow(pair,timeframe,frames[pair],optimizer?.settings,strategy);return{...row,optimizerAvailable:Boolean(optimizer?.available),configurationSource:optimizer?.source||null,configurationComputedAt:optimizer?.computedAt||null,configurationStamp:optimizer?.stamp||null,frameErrors:frameErrors[pair]};});
  const coverage=rows.filter(row=>row.available).length,value={capitalizationVersion:COMPOUND_CAPITALIZATION_VERSION,protocolVersion:COMPOUND_MCP_PROTOCOL_VERSION,source:"MCP_SERVER_CAPITALIZATION_DATA_PLANE",timeframe,strategy,total:PAIRS.length,coverage,failureCount:PAIRS.length-coverage,hierarchy,requestedBarsPerFrame:CAPITALIZATION_REQUEST_BARS,optimizerCoverage:projection.coverage,generatedAt:new Date().toISOString(),durationMs:Date.now()-started,rows};
  mcpCapitalizationCache.clear();mcpCapitalizationCache.set(cacheKey,{expires:Date.now()+MCP_CAPITALIZATION_CACHE_MS,value});return value;
}
function mcpResult(value){return{content:[{type:"text",text:JSON.stringify(value)}]};}
async function handleMcp(request,env,ctx){await requireCloudflareAccess(request,env);assertSameOrigin(request);if(request.method!=="POST")return json({error:"MCP requires POST."},405);const body=await request.json().catch(()=>null),id=body?.id??null;if(body?.jsonrpc!=="2.0")return json({jsonrpc:"2.0",id,error:{code:-32600,message:'Invalid Request: jsonrpc must be "2.0"'}});try{let result;if(body.method==="initialize")result={protocolVersion:COMPOUND_MCP_PROTOCOL_VERSION,capabilities:{tools:{}},serverInfo:{name:"cte-compound-data-plane",version:COMPOUND_SCHEDULE_VERSION}};else if(body.method==="tools/list")result={tools:MCP_TOOLS};else if(body.method==="tools/call"){const name=body?.params?.name,args=body?.params?.arguments||{};if(name==="get_compound_schedule")result=mcpResult(await liveCompoundSchedule(request,env,ctx,args?.strategies||["ASSET"]));else if(name==="get_capitalization_snapshot")result=mcpResult(await liveCapitalizationSnapshot(request,env,ctx,args?.timeframe||"H1",args?.strategy||"ASSET"));else throw Object.assign(new Error(`Unknown MCP tool: ${name||""}`),{code:-32601});}else throw Object.assign(new Error(`Method not found: ${body?.method||""}`),{code:-32601});return json({jsonrpc:"2.0",id,result});}catch(error){return json({jsonrpc:"2.0",id,error:{code:Number(error?.code)||-32603,message:String(error?.message||error)}});}}
async function handleScheduleProjection(request,env){await requireCloudflareAccess(request,env);assertSameOrigin(request);return json(await optimizerScheduleProjection(env));}

function injectPlatformContracts(response,url){return (async()=>{const type=response.headers.get("Content-Type")||"";if(!(url.pathname==="/"||url.pathname.endsWith(".html")||type.includes("text/html")))return response;let html=await response.text();html=html.replace('<script src="/market-mentor.js"></script>','<script src="/market-mentor.js"></script>\n  <script src="/indicator-only.js"></script>');html=html.replace('<script src="/htl-horizon-contract.js"></script>','<script src="/mcp-schedule-data-plane.js"></script>\n  <script src="/mcp-capitalization-data-plane.js"></script>\n  <script src="/htl-horizon-contract.js"></script>');html=html.replace('<script src="/platform-horizon-runtime.js"></script>','<script src="/horizon-strategy-contract.js"></script>\n  <script src="/platform-horizon-runtime.js"></script>\n  <script src="/platform-horizon-qualified-direction.js"></script>');
html=html.replace('  function scheduleRequestCount(instrument,timeframe){const config=resolvedConfiguration(instrument,timeframe),length=strategyHistoryLength(config,state.selectedScheduleStrategy),analytical=indicatorWarmupBars(state.selectedScheduleStrategy,length)+60,event=(Math.max(3,Number(state.engineConfig?.htlLength)||10)*3)+60;return clamp(Math.ceil(Math.max(180,analytical,event)),180,MAX_ANALYTICAL_HISTORY);}','  function scheduleRequestCount(instrument,timeframe){const config=resolvedConfiguration(instrument,timeframe),length=strategyHistoryLength(config,state.selectedScheduleStrategy),configuredMax=Math.max(200,...Object.values(config||{}).map(item=>Number(item?.length)||0)),analytical=indicatorWarmupBars(state.selectedScheduleStrategy,length)+60,event=(Math.max(3,Number(state.engineConfig?.htlLength)||10)*3)+60,floor=(configuredMax*2)+2;return clamp(Math.ceil(Math.max(180,floor,analytical,event)),180,MAX_ANALYTICAL_HISTORY);}');
html=html.replace('  async function loadSchedule(mode="full") {\n    if(!marketDataReady())return;','  async function loadSchedule(mode="full") {\n    if(!marketDataReady())return;\n    if(globalThis.CTECompoundMcpSchedule){try{const snapshot=await globalThis.CTECompoundMcpSchedule.prime(state.selectedScheduleStrategy,state.engineConfig?.strategy||"ASSET");if(snapshot?.rows?.length){state.scheduleFailures.clear();for(const pair of INSTRUMENTS)for(const timeframe of TIMEFRAMES)state.scheduleEvaluations.delete(scheduleKey(pair,timeframe));for(const row of snapshot.rows){const key=scheduleKey(row.pair,row.timeframe);if(row.available){state.scheduleEvaluations.set(key,{latest:row.strategies||{},mcp:true,completedCandleTime:row.completedCandleTime,currentPrice:row.currentPrice});renderScheduleCell(row.pair,row.timeframe);}else state.scheduleFailures.set(key,{instrument:row.pair,timeframe:row.timeframe,error:row.error||"MCP schedule unavailable",attempts:1});}const total=INSTRUMENTS.length*TIMEFRAMES.length,available=state.scheduleEvaluations.size;el("progressFill").style.width=`${available/total*100}%`;el("progressText").textContent=`MCP ${available} / ${total}${state.scheduleFailures.size?` · ${state.scheduleFailures.size} unresolved`:" · ready"}`;el("scheduleStamp").textContent=`MCP schedule ${new Date().toLocaleTimeString()} · completed candles only`;document.querySelectorAll(".signal-cell.loading").forEach(cell=>cell.classList.remove("loading"));renderMtfForecast();queueAutomaticOptimization();setTimeout(()=>{if(marketDataReady()&&!state.chartLoading)void runPlatformDiagnostic(false);},300);return;}}catch(error){console.error("MCP schedule data plane failed; using bounded candle fallback",error);}}');
html=html.replace('  function mtfEventRow(pair,timeframe){const candles=state.scheduleCandles.get(scheduleKey(pair,timeframe));if(!candles?.length)return null;const cacheKey=`${pair}|${timeframe}|${state.engineConfig.htlLength}|${candles.at(-1).time}`;if(!state.mtfEventCache.has(cacheKey))state.mtfEventCache.set(cacheKey,buildEventRow(pair,candles,state.engineConfig.htlLength));return state.mtfEventCache.get(cacheKey);}','  function mtfEventRow(pair,timeframe){const candles=state.scheduleCandles.get(scheduleKey(pair,timeframe));if(!candles?.length){const row=globalThis.CTECompoundMcpSchedule?.get?.(pair,timeframe),event=row?.htlCurrentEvent;if(!event||event.currentEvent==="—")return null;return{pair,currentEvent:event.currentEvent,currentEventOpen:event.openPrice??null,currentEventStart:event.startTime??null,mcp:true};}const cacheKey=`${pair}|${timeframe}|${state.engineConfig.htlLength}|${candles.at(-1).time}`;if(!state.mtfEventCache.has(cacheKey))state.mtfEventCache.set(cacheKey,buildEventRow(pair,candles,state.engineConfig.htlLength));return state.mtfEventCache.get(cacheKey);}');
html=html.replace('</body>','  <script src="/unified-chart.js"></script>\n  <script src="/chart-indicator-ownership.js"></script>\n  <script src="/chart-ioi-iom.js"></script>\n  <script src="/directional-ownership.js"></script>\n  <script src="/ioi-iom-performance.js"></script>\n  <script src="/htl-schedule-integrity.js"></script>\n  <script src="/analytical-facilities.js"></script>\n  <script src="/forensic-runtime-repair.js"></script>\n  <script src="/schedule-dataset-accounting.js"></script>\n  <script src="/htl-signal-panel.js"></script>\n  <script src="/analytical-table-sorting.js"></script>\n  <script src="/runtime-integrity.js"></script>\n  <script src="/chart-crossing-arrows.js"></script>\n</body>');const responseHeaders=new Headers(response.headers);responseHeaders.delete("Content-Length");responseHeaders.set("Cache-Control","no-store");return new Response(html,{status:response.status,statusText:response.statusText,headers:responseHeaders});})();}

export default{
  async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/mcp")return handleMcp(request,env,ctx);if(url.pathname==="/api/engine/schedule"&&request.method==="GET")return handleScheduleProjection(request,env);if(url.pathname==="/api/oanda/order"&&request.method==="POST"){try{assertSameOrigin(request);const io=await indicatorOnlyAuthority(env);if(io.enabled)return json({error:`Indicator Only is active for ${io.ticketCount||1} ticket${Number(io.ticketCount||1)===1?"":"s"}. Disengage IO before submitting a manual order.`,indicatorOnly:io},409);}catch(error){if(Number(error?.status)===403)return json({error:error?.message||"Order rejected."},403);if(String(error?.message||"").startsWith("Indicator Only is active"))return json({error:error.message},409);if(error?.message?.includes("Cross-" )||error?.message?.includes("Browser-origin"))return json({error:error.message},403);return json({error:"Order route authority unavailable; order withheld.",details:error?.message||String(error)},503);}}return injectPlatformContracts(await horizonWorker.fetch(request,env,ctx),url);},
  async scheduled(event,env,ctx){return horizonWorker.scheduled(event,env,ctx);}
};